name: Clean VLESS Subscription

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone source repo
        run: |
          git clone https://github.com/HadiDastangoo/TelegramV2RayExtractor.git repo

      - name: Merge files
        run: |
          cat repo/subscriptions/vless/* > all.txt

      - name: Filter only valid VLESS
        run: |
          grep '^vless://' all.txt > vless.txt

      - name: Remove duplicates
        run: |
          sort vless.txt | uniq > clean.txt

      - name: Remove empty lines
        run: |
          sed '/^$/d' clean.txt > final.txt

      - name: Convert to Base64
        run: |
          base64 final.txt > sub.txt

      - name: Push result
        run: |
          git init
          git config user.name "bot"
          git config user.email "bot@github.com"
          git add sub.txt
          git commit -m "update clean sub" || echo "no change"
          git branch -M main
          git remote add origin https://github.com/SMaryamHosseini/Mysub.git
          git push -f origin main
